### ISSUE TITLE
[vSphere][7.0][vsphere][ansible][vmware-vm-7.0-stig-ansible-hardening] Incorrect directory created 

### ISSUE THREAD

**Issue by Mapmark** [vmware/dod-compliance-and-automation#182]
### Describe the bug

When utilizing the VM-remediation  role and leveraging powercli modules. The directory that is meant to hold the modules is being incorrectly populated. 

```
---
# Test playbook 

- hosts: localhost  
  pre_tasks:
    - name: Set appropriate values 
      set_fact: 
        copy_powercli_modules: true 
  roles:
    - role: stig_vm-remediation
    
```

Prelim.yml 
``` 
- name: Copy PowerCLI Modules in Place
  ansible.posix.synchronize:
    src: "{{ role_path }}/{{ file_location }}/Modules/"
    dest: /root/.local/share/powershell/Modules\
  when:
    - copy_powercli_modules
 ``` 
 
 
 Upon running, the directory structure is as such, with the `modules` path being empty and not having the modules included. even after creating a folder for `modules` in the `files` directory for the role. 

```
ls  /root/.local/share/powershell/
 Modules  'Modules\'   PSReadLine   Scripts
```

### Reproduction steps

```
---
# Test playbook 

- hosts: localhost  
  pre_tasks:
    - name: Set appropriate values 
      set_fact: 
        copy_powercli_modules: true 
  roles:
    - vm-remediation
    
 ```

### Expected behavior

The expected behavior for it, would be the directory structure being placed in the correct spot. 

Prelim.yml 
```
- name: Copy PowerCLI Modules in Place
  ansible.posix.synchronize:
    src: "{{ role_path }}/{{ file_location }}/Modules/"
    dest: /root/.local/share/powershell/Modules/
  when:
    - copy_powercli_modules
```

```
ls  /root/.local/share/powershell/Modules/
VMware.CloudServices                                 VMware.Sdk.vSphere.Content                      VMware.Sdk.vSphere.vCenter.Tagging
...redacted
```
