### ISSUE TITLE
[vSphere][8.0][postgresql] VCPG-80-000005 implicit other task

### ISSUE THREAD

**Issue by cbreuil-orange** [vmware/dod-compliance-and-automation#293]
### Describe the bug

Hi

if you run only the tag of rule VCPG-80-000005 the script /opt/vmware/vpostgres/current/bin/vmw_vpg_config/vmw_vpg_config.py modify config file for another task like VCPG-80-000007,
so when you need to not execute VCPG-80-000007 you need to disable also VCPG-80-000005

```
root@vcenter [ ~ ]# ls /storage/db/vpostgres/stig.conf
ls: cannot access '/storage/db/vpostgres/stig.conf': No such file or directory

root@vcenter [ ~ ]# /opt/vmware/vpostgres/current/bin/vmw_vpg_config/vmw_vpg_config.py --action stig_enable --pg-data-dir /storage/db/vpostgres
2025-04-11T13:14:16.537Z  Retrieving current TCP listen port for postgres server
2025-04-11T13:14:16.537Z  port defined in /storage/db/vpostgres/postgresql.conf as 5432
2025-04-11T13:14:16.542Z  Updated /storage/db/vpostgres/postgresql.conf
2025-04-11T13:14:16.542Z  STIG configuration has been enabled. A reboot of the host is required.
2025-04-11T13:14:16.542Z  Removing temp file /tmp/tmpj0o830s7
root@vcenter [ ~ ]# ls /storage/db/vpostgres/stig.conf
/storage/db/vpostgres/stig.conf

root@vcenter [ ~ ]# cat /storage/db/vpostgres/stig.conf
log_connections = on
log_disconnections = on
log_line_prefix = '%m %c %x %d %u %r %p %l'
pgaudit.log_catalog = on
pgaudit.log_level = log
pgaudit.log_parameter = on
pgaudit.log_relation = on
pgaudit.log = 'all, -misc'
password_encryption = scram-sha-256
client_min_messages = error
```

So i think we need to adapt the task to only modify the file wanted by the VCPG-80-000005 rule

```
root@venter [ ~ ]# diff /storage/db/vpostgres/postgresql.conf /tmp/postgresql.conf
706c706
< shared_preload_libraries = 'health_status_worker,pg_stat_statements,pgaudit'
---
> shared_preload_libraries = 'health_status_worker,pg_stat_statements'
```

i purpose

```
- name: Run vmw_vpg_config script to enable STIG settings
  tags: [VCPG-80-000005]
  when: run_vmw_pg_config | bool
  block:
    - name: VCPG-80-000005 - Enable pgaudit libraries
      ansible.builtin.lineinfile:
        path: '{{ var_postgresql_conf_path }}'
        state: present
        regexp: "^shared_preload_libraries = '(?!.*pgaudit)(.*)'"
        line: "shared_preload_libraries = '\\1,pgaudit'"
        backrefs: yes
      notify:
        - '{{ role_name }} : restart {{ var_notify_service_name }}'
```

Result 
```
Firts Launch

TASK [dod-compliance-and-automation-github/dod-compliance-and-automation/vsphere/8.0/v2r2-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/roles/postgresql : VCPG-80-000005 - Enable pgaudit libraries] ***

--- before: /storage/db/vpostgres/postgresql.conf (content)
+++ after: /storage/db/vpostgres/postgresql.conf (content)

@@ -703,7 +703,7 @@

# - Shared Library Preloading -
-shared_preload_libraries = 'health_status_worker,pg_stat_statements'
+shared_preload_libraries = 'health_status_worker,pg_stat_statements,pgaudit'
#local_preload_libraries = ''
session_preload_libraries = 'auto_explain'
#jit_provider = 'llvmjit'              # JIT library to use
 
changed: [vcenter]

second launch
 
TASK [dod-compliance-and-automation-github/dod-compliance-and-automation/vsphere/8.0/v2r2-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/roles/postgresql : VCPG-80-000005 - Enable pgaudit libraries] ***

ok: [vcenter]
```

its also add Idempotency 

Original code
https://github.com/vmware/dod-compliance-and-automation/blob/4c69b84a0be4f8ba3e43aa1cd1b8a7c7c8d88fd2/vsphere/8.0/v2r2-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/roles/postgresql/tasks/postgresql.yml#L29-L63
