### ISSUE TITLE
VCSA 7.0 perfcharts role is missing some variables and fails to run.

### ISSUE THREAD

**Issue by Aggraxis** [vmware/dod-compliance-and-automation#85]
### Describe the bug

The perfcharts role is missing a few variables:
   - var_server_xml_show_server_info
   - var_server_xml_show_server_report
   - var_server_xml_server

Ansible output:
```
{
    "msg": "The task includes an option with an undefined variable. The error was: 'var_server_xml_show_server_info' is undefined\n\nThe error appears to be in '/tmp/awx_6354_332x62lu/project/vmware/7.0/vcsa/roles/perfcharts/tasks/perfcharts.yaml': line 863, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: VCPF-70-000025 - Performance Charts must be configured to not show error reports.\n  ^ here\n",
    "_ansible_no_log": false
}
```

### Reproduction steps

```bash
1. Run Playbook
2. Playbook fails for undefined variable error.
```

### Expected behavior

The variables need to be defined in vars/main.yml for the perfcharts role.

```
#had to add these to vars/main.yml
var_server_xml_show_server_info: "false"
var_server_xml_show_server_report: "false"
var_server_xml_server: "Anonymous"
```

### Additional context

Playbook ran fine after defining the variables.

**Comment by Aggraxis** [comment]
var_server_xml_server is still missing in the pull request from #87. 

It is referenced in this task:

```
# Title: Performance Charts must hide the server version.

- name: VCPF-70-000026 - Performance Charts must hide the server version.
  community.general.xml:
    path: '{{ var_server_xml_path }}'
    xpath: '/Server/Service/Connector'
    attribute: 'server'
    value: '{{ var_server_xml_server }}'
  tags:
    - VCPF-70-000026
  notify:
    - restart perfcharts
  when:
    - run_server_anonymous | bool

```
